image: registry.gitlab.com/showcheap/android-ci:master

before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./gradlew
    - sdkmanager "platforms;android-22"         # Specify compileSdkVersion Depends on your android project
    - sdkmanager "build-tools;25.0.3"           # Specify build tool to install, depends on your android project
    - sdkmanager "extras;android;m2repository"  # You can add sdkmanager command to install another package here
    - sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" # If you need constraint-layout support


cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
     - .gradle/

stages:
  - build
  - test

build:
    stage: build
    script:
       - ./gradlew assemble

test:
  stage: test
  script:
     - ./gradlew check

